name: Build Deb packages

on:
  push:
    branches: ["latest"]
  pull_request:
    paths:
      - 'ros-apt-source/**'
      - 'Earthfile'
  workflow_dispatch:
defaults:
    run:
      working-directory: ./ros-apt-source
jobs:
  build-ros2-apt-source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu:focal,ubuntu:jammy,ubuntu:noble ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Earthly
        run: |
          sudo wget 'https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64' -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build apt-source deb
        run: earthly +ros-apt-source --distro=${{ matrix.distro }}
      - name: Test ros 2 apt-source deb 
        run:  | 
              earthly +test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros2
              earthly +test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros2-testing

  build-ros-apt-source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu:focal]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Earthly
        run: |
          sudo wget 'https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64' -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build apt-source deb
        run: earthly +ros-apt-source --distro=${{ matrix.distro }}
      - name: Test ros 2 apt-source deb 
        run:  | 
              earthly +test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros --version=ros
              earthly +test-aptsource-pkg-install --distro=${{ matrix.distro }} --repo=ros-testing --version=ros
  ros2-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu:focal,ubuntu:jammy,ubuntu:noble ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Earthly
        run: |
          sudo wget 'https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64' -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build packages integration
        run: | 
              earthly +ros-apt-source --distro=${{ matrix.distro }}
      - name: Test integration
        run: | 
              earthly +ros2-test-repos --distro=${{ matrix.distro }}
              earthly +ros2-test-repos --distro=${{ matrix.distro }} --package=ros2-testing-apt-source
              earthly +integration-check-switch --distro=${{ matrix.distro }}
  ros-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu:focal]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Earthly
        run: |
          sudo wget 'https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64' -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build packages integration
        run: | 
              earthly +ros-apt-source --distro=${{ matrix.distro }}
      - name: Test integration
        run: | 
              earthly +ros-test-repos --distro=${{ matrix.distro }}
              earthly +ros-test-repos --distro=${{ matrix.distro }} --package=ros-testing-apt-source
              earthly +integration-check-switch --distro=${{ matrix.distro }} --repo=ros
